image: Visual Studio 2022

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

build_script:
  - yarn install
  - yarn run publish

test: off
