image: Visual Studio 2022

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - yarn install

build_script:
  - set DEBUG=electron-forge:require-search && yarn run publish

test: off
