image: Visual Studio 2022

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 16 x64

build_script:
  - npm run release

test: off
