image: Visual Studio 2022

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - npm install

build_script:
  - npm run publish

test: off
